language: android

jdk:
- oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - addon-google_apis-google-24

before_install:
- chmod +x gradlew
- export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
- export JAVA_HOME=$JAVA8_HOME
- yes | sdkmanager "platforms;android-27"

after_success:
- ./gradlew coveralls
- chmod +x ./upload-gh-pages.sh
- chmod +x ./import-translations-github.sh
- ./import-translations-github.sh
- ./upload-gh-pages.sh

script:
- cd $TRAVIS_BUILD_DIR/
- ./gradlew testDebugUnitTest assembleDebug jacocoTestReport

notifications:
  slack: diabetesmonitoring:uk2xb9sAxOaVedj7zePyuBqa

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
